<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find flex_gazebo)/urdf/truss/2d/tomato.gazebo.xacro" />

  <xacro:macro name="truss" params="*origin">
    <xacro:property name="height" value="0.10" />
    <xacro:property name="width" value="0.18" />
    <xacro:property name="length" value="0.15" />
    <xacro:property name="size" value="${length} ${width} ${height}" />

    <joint name="tomato_joint" type="floating">
      <xacro:insert_block name="origin" />
      <parent link="world"/>
      <child link="tomato_link" />
    </joint>


    <link name="tomato_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size = "${size}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size = "${size}" />
        </geometry>
        <material name="Blue"/>
      </visual>

      <inertial>
        <origin xyz="${length/2} ${width/2} ${height/2}" rpy="0 0 0"/>
        <parent link="world"/>
        <mass value="10"/>
        <inertia
	         ixx="1.0" ixy="0.0" ixz="0.0"
           iyy="1.0" iyz="0.0"
           izz="1.0"/>
       </inertial>
     </link>

     <xacro:tomato_gazebo/>
  </xacro:macro>
</robot>
