<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find flex_gazebo)/urdf/truss/3d/tomato.xacro"/>
  <xacro:include filename="$(find flex_gazebo)/urdf/truss/3d/peduncle.xacro"/>

  <xacro:macro name="truss" params="*origin">
    <xacro:property name="tomato_radius" value="0.05" />
    <xacro:property name="peduncle_length" value="0.1" />
    <xacro:property name="peduncle_radius" value="0.01" />


    <xacro:peduncle peduncle_length="${peduncle_length}"
      peduncle_radius="${peduncle_radius}"
      parent_link="world"/>


    <xacro:tomato tomato_name="1" radius="${tomato_radius}" parent_link="peduncle">
          <origin xyz="${peduncle_length/2 + tomato_radius} 0 0" rpy="0 0 0" />
    </xacro:tomato>

    <xacro:tomato tomato_name="2" radius="${tomato_radius}" parent_link="peduncle">
          <origin xyz="${-peduncle_length/2 - tomato_radius} 0 0" rpy="0 0 0" />
    </xacro:tomato>

  </xacro:macro>
</robot>
