controller_list:
  - name: fake_manipulator_controller
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  - name: fake_hand_controller
    joints:
      - sdh_finger_22_joint
      - sdh_finger_23_joint
      - sdh_knuckle_joint
      - sdh_finger_12_joint
      - sdh_finger_13_joint
      - sdh_thumb_2_joint
      - sdh_thumb_3_joint